services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  App\Controller\IndexController:
    arguments:
      $renderer: '@templating.engine.twig'

  App\Controller\CreateController:
    arguments:
      $manager: '@App\Manager\ItemManager'

  App\Controller\ListController:
    arguments:
      $manager: '@App\Manager\ItemManager'

  App\Controller\CheckController:
    arguments:
      $manager: '@App\Manager\ItemManager'

  App\Controller\DeleteController:
    arguments:
      $manager: '@App\Manager\ItemManager'