index:
  path: /
  controller: App\Controller\IndexController

list:
  path: /items
  controller: App\Controller\ListController
  methods: GET
  defaults:
    _format: json

create:
  path: /item/create
  controller: App\Controller\CreateController
  methods: POST
  defaults:
    _format: json

delete:
  path: /item/{uuid}/delete
  controller: App\Controller\DeleteController
  methods: DELETE
  defaults:
    _format: json

check:
  path: /item/{uuid}/check
  controller: App\Controller\CheckController
  methods: PATCH
  defaults:
    isChecked: true
    _format: json

uncheck:
  path: /item/{uuid}/uncheck
  controller: App\Controller\CheckController
  methods: PATCH
  defaults:
    isChecked: false
    _format: json