parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false

    App\Controller\IndexController:
        arguments:
            $renderer: '@templating.engine.twig'
        public: true

    App\Controller\CreateController:
        arguments:
            $manager: '@App\Manager\ItemManager'
        public: true

    App\Controller\ListController:
        arguments:
            $manager: '@App\Manager\ItemManager'
        public: true

    App\Controller\CheckController:
        arguments:
            $manager: '@App\Manager\ItemManager'
        public: true

    App\Controller\DeleteController:
        arguments:
            $manager: '@App\Manager\ItemManager'
        public: true

    App\Repository\ItemRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'App\Entity\Item'

    App\Manager\ItemManager:
        arguments:
            $objectManager: '@doctrine.orm.default_entity_manager'
            $repository: '@App\Repository\ItemRepository'

    App\DataFixtures\ItemFixtures:
        tags:
            - {name: 'doctrine.fixture.orm' }