parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false

    App\Repository\ItemRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'App\Entity\Item'

    App\Manager\ItemManager:
        arguments:
            $objectManager: '@doctrine.orm.default_entity_manager'
            $repository: '@App\Repository\ItemRepository'

    App\DataFixtures\ItemFixtures:
        tags:
            - {name: 'doctrine.fixture.orm' }